### ISSUE TITLE
ai.thermometer on Jetson Nano 2Gb

### ISSUE THREAD

**Issue by nanogear** [tomek-l/ai-thermometer#15]
Hello,

Do you know if the AI.thermometer can work in the new Jetson Nano 2Gb or I need to modify the code?

Thank you and best regards

**Comment by tomasz-lewicki** [comment]
Hi there!

Yes, it will work with the 2GB version :)
Some other applications might be moved to swapfile, so a fast SD card is
recommended.



pon., 26 paź 2020 o 11:45 nanogear <notifications@github.com> napisał(a):

**Comment by nanogear** [comment]
Thank you for your kind reply!!!
