### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by nanogear** [tomek-l/ai-thermometer#17]
Hello, need some advice please.. why I am getting syntax error when executing Capture Images.ipynb example?

Thank you and Regards!!!

`!gst-launch-1.0 v4l2src device=/dev/video1 num-buffers=1 ! video/x-raw,format=GRAY16_LE ! videoconvert ! pngenc ! filesink location="$save_path"`

**Comment by tomasz-lewicki** [comment]
Hi nanogear!

Are you executing this line within a notebook or in a shell?
1) If in the notebook, could you show the error you're getting?
2) If in the shell, remove the preceding '!' from the command and provide a
specific file location, like so:
gst-launch-1.0 v4l2src device=/dev/video1 num-buffers=1 !
video/x-raw,format=GRAY16_LE ! videoconvert ! pngenc ! filesink
location=/tmp/image.png

Let me know if this helps!

Tomasz

pon., 16 lis 2020 o 12:38 nanogear <notifications@github.com> napisał(a):

**Comment by nanogear** [comment]
Thank you Thomasz 

It worked now. Executing in the notebook.
