### ISSUE TITLE
Camera Issue

### ISSUE THREAD

**Issue by BasilHarun** [tomek-l/ai-thermometer#42]
![PHOTO-2021-08-16-14-40-30](https://user-images.githubusercontent.com/88293565/129531811-3b9df538-1e21-4fae-b5aa-e22e0ce573de.jpg)

can you help me with this erroor

**Comment by tomasz-lewicki** [comment]
Hi there!

This should help :slightly_smiling_face: 
```shell
echo 'SUBSYSTEM=="usb",  ENV{DEVTYPE}=="usb_device", GROUP="plugdev", MODE="0664"' | sudo tee /etc/udev/rules.d/10-libuvc.rules 
sudo udevadm trigger
```

You can read more about this in the [FAQ](https://github.com/tomek-l/ai-thermometer/blob/master/README.md#faqcommon-issues)

**Comment by BasilHarun** [comment]
Hi, 

Thanks for replying, I’ve tried it out but see everytime it gives different error 
resize error is due to it doesn't detect pi camera
and waiting for ir frames is due to empty pipline of ir thread

![4C492EA4-872C-48E7-9F0D-18F8C84C0DE7](https://user-images.githubusercontent.com/88293565/129610934-78bef865-8cc4-49b2-8bd8-e2bc13a0306c.jpeg)


The only thing I think I’m using Nano 2Gb could it be because of the memory.

**Comment by BasilHarun** [comment]
Error 1 

![27381ED8-F49E-417B-A96F-87D5FD482B6D](https://user-images.githubusercontent.com/88293565/129612222-c2387964-f132-4ce5-bf09-5bf1995d6e9e.png)


Error 2 

![BE465A93-DAD8-45A9-BC9D-C25259C67CE4](https://user-images.githubusercontent.com/88293565/129612300-6f1e015a-30fd-46fa-b840-4effe617b5b9.png)

**Comment by BasilHarun** [comment]
![Uploading 3A799CD2-0BA0-4BD8-8A8D-C5EB8D075842.png…]()

**Comment by tomasz-lewicki** [comment]
Yeah, so those are two separate issues:
1) with Pi Camera 
2) with USB permissions for Lepton 3.

To try addressing 1) I'd start by restarting argus:
```shell
sudo systemctl restart nvargus-daemon.service
```
After restart, try this:
```shell
gst-launch-1.0 nvarguscamerasrc ! 'video/x-raw(memory:NVMM),  width=(int)1920, height=(int)1080, format=(string)NV12,  framerate=(fraction)30/1' ! nvoverlaysink
```
Can you see video on the screen?

Regarding 2): are you still seeing `uvc_open error -3`?

**Comment by BasilHarun** [comment]
Hi, 

I did all the steps accordingly, and can see the video. 

Then I ran Python3 Main.py, 

on side note (I had a low memory warning on right hand corner.)

this is the result. 

![3D14822E-10F3-46D2-B973-987943AC3863](https://user-images.githubusercontent.com/88293565/129614749-36c04afb-6b63-47fc-8976-64cc593bc7ae.png)

![59ABA8E1-75A9-45B3-B188-4647E8EC7730](https://user-images.githubusercontent.com/88293565/129614810-ef8909c8-52e0-4b0c-b0f6-c38f893fed39.png)

**Comment by BasilHarun** [comment]
After fixing RGB Error, it gives me the IR error. 

![3AD2AC08-7B58-453C-88B3-A1A6A5C03C65](https://user-images.githubusercontent.com/88293565/129645630-e897289a-974b-4cd4-a82a-272e4b2f4503.jpeg)

**Comment by BasilHarun** [comment]
Also I’m Using Jetson Nano 2GB not 4GB and when I run main.py it always gives me this error on side. 

![6595C77B-4F51-4333-90AA-70155764B749](https://user-images.githubusercontent.com/88293565/129645974-812ad31f-8f19-4c51-b1e9-71af14bd4e1b.jpeg)

**Comment by BasilHarun** [comment]
When I run the IR camera individually, I get this empty error. 

![8C01806F-1714-4F5D-8EDD-F7F93145C070](https://user-images.githubusercontent.com/88293565/129647470-998c53f7-9b10-4a3f-8b9b-602bcc441724.jpeg)
