### ISSUE TITLE
Program/camera feed over http

### ISSUE THREAD

**Issue by antonislekkas** [tomek-l/ai-thermometer#49]
Hello, I've been wondering if it is possible to access the feed the program provides(thermal and normal camera, along with the temperature overlay) so i can stream it over http. For the streaming I usually use VLC's component. My main issue is that I cannot find a way to access the feed. Is it saved locally somewhere? Am I missing something? Thanks for your time

**Comment by tomasz-lewicki** [comment]
Hi @MrAntony44,

Some work in that regard has been done a long while ago in the [http_streaming branch](https://github.com/tomek-l/ai-thermometer/tree/http_streaming). Please consider taking a look!

**Comment by antonislekkas** [comment]
will have a look. Thanks for the reference and thanks for the amazing repo!
