### ISSUE TITLE
Question about face detection

### ISSUE THREAD

**Issue by nanogear** [tomek-l/ai-thermometer#9]
Hello, thank you very much for your codes. 

Just want to know if the face detection is possible if a person is using a mask. Thank you in advance!

**Comment by tomasz-lewicki** [comment]
Hey @nanogear ,

Yes, however you should expect lower accuracy.

The detector in this repository is an SSD detector trained on the FDDB dataset.
The dataset doesn't contain samples with masks, but I had some success testing the detection with a mask on.

**Comment by nanogear** [comment]
I see, thank you for answer me!!! Regards!
